#Numpy
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

#Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [6]:
print(a[0],a[1],a[2])

1 2 3


# Array indexing
Numpy offers several ways to index into arrays.

In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [8]:
b = a[:2, 1:3]

In [9]:
print(b)

[[2 3]
 [6 7]]


In [10]:
print(a[0,1])

2


In [11]:
x = np.array([1, 2])   
print(x.dtype) 

int64


In [12]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)


print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [13]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [14]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [15]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [16]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])


print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


. All 0s and all 1s matrix

In [18]:
#This will create a matrix of given shape such that all elements in it are zeroes
matrix1 = np.zeros((3,4))
print(matrix1)

matrix2 = np.ones((4,3))
print(matrix2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
#Create an all zeroes matrix with 9 columns and 3 rows
print(np.zeros((3,9)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [20]:
#create a matrix with a given number N of shape mxn
matrix3 = np.full((3,4),96)
print(matrix3)

[[96 96 96 96]
 [96 96 96 96]
 [96 96 96 96]]


In [21]:
matrix4 = np.random.randint(10,size=(4,4))
print(matrix4)
#note that 10 is excluded

#creating a matrix with random integers from 11 to 20
matrix5 = np.random.randint(11,21, size =(3,3))
print(matrix5)
#note that 11 is included, 21 is excluded

[[1 2 9 7]
 [7 5 0 6]
 [3 4 9 8]
 [5 8 6 0]]
[[18 14 13]
 [19 15 15]
 [12 19 13]]


# Mathematical Operations on Matrices
Addition, Subtraction

In [22]:
#One of the advantages of using numpy is that we can straightaway add numbers to an entire array
#for example:
matrix8 = np.array([[1,2,3],[4,5,6]])
matrix9 = matrix8 + 1
print(matrix9)

[[2 3 4]
 [5 6 7]]


In [23]:
matrix10 = np.array([10,20,30,40,50,60,70,80,90,100])
matrix11 = matrix10/10
print(matrix11)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [24]:
matrix12 = matrix11 * 10
print(matrix12)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
